name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile

  security-check:
    needs: compile
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Trivy Installation
      run: |
              sudo apt-get update -y
              sudo apt-get install -y wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
              sudo apt-get update -y
              sudo apt-get install -y trivy

    - name: Trivy Repo Scan
      run: trivy fs --format json --output fs-report.json .

    - name: GitLeaks Installation
      run: sudo apt install gitleaks -y
    
    - name: GitLeaks Scan
      run: gitleaks detect source . -r gitleaks-report.json -f json

  unit_tests:
    needs: security-check
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit tests with Maven
      run: mvn test

